print('Python 中运算符的优先级')
print('1-函数调用、寻址、下标')
print('2-幂运算 **')
print('3-翻转运算 ~')
print('4-正负号 + -')
print('5-乘除 除余  * / %')
print('6- 加减 + -')
print('7- 移位 << >>')
print('8-按位与 或 异或 & ^ |')
print('9-比较运算符 < > <= >= ==')
print('10-逻辑与或非 not and or')
print('11-lambda表达式')
input('The end')
